package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ActivityMatchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityMatchAllPropertiesEquals(ActivityMatch expected, ActivityMatch actual) {
        assertActivityMatchAutoGeneratedPropertiesEquals(expected, actual);
        assertActivityMatchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityMatchAllUpdatablePropertiesEquals(ActivityMatch expected, ActivityMatch actual) {
        assertActivityMatchUpdatableFieldsEquals(expected, actual);
        assertActivityMatchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityMatchAutoGeneratedPropertiesEquals(ActivityMatch expected, ActivityMatch actual) {
        assertThat(expected)
            .as("Verify ActivityMatch auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityMatchUpdatableFieldsEquals(ActivityMatch expected, ActivityMatch actual) {
        assertThat(expected)
            .as("Verify ActivityMatch relevant properties")
            .satisfies(e -> assertThat(e.getActivityType()).as("check activityType").isEqualTo(actual.getActivityType()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getMatchDate()).as("check matchDate").isEqualTo(actual.getMatchDate()))
            .satisfies(e -> assertThat(e.getMatchTime()).as("check matchTime").isEqualTo(actual.getMatchTime()))
            .satisfies(e -> assertThat(e.getLocation()).as("check location").isEqualTo(actual.getLocation()))
            .satisfies(e -> assertThat(e.getNotes()).as("check notes").isEqualTo(actual.getNotes()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()))
            .satisfies(e -> assertThat(e.getResponseAt()).as("check responseAt").isEqualTo(actual.getResponseAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityMatchUpdatableRelationshipsEquals(ActivityMatch expected, ActivityMatch actual) {
        assertThat(expected)
            .as("Verify ActivityMatch relationships")
            .satisfies(e -> assertThat(e.getRatings()).as("check ratings").isEqualTo(actual.getRatings()))
            .satisfies(e -> assertThat(e.getMatchRequestor()).as("check matchRequestor").isEqualTo(actual.getMatchRequestor()))
            .satisfies(e -> assertThat(e.getUserDetails()).as("check userDetails").isEqualTo(actual.getUserDetails()))
            .satisfies(e -> assertThat(e.getMatchedActivity()).as("check matchedActivity").isEqualTo(actual.getMatchedActivity()));
    }
}
