package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ActionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActionAllPropertiesEquals(Action expected, Action actual) {
        assertActionAutoGeneratedPropertiesEquals(expected, actual);
        assertActionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActionAllUpdatablePropertiesEquals(Action expected, Action actual) {
        assertActionUpdatableFieldsEquals(expected, actual);
        assertActionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActionAutoGeneratedPropertiesEquals(Action expected, Action actual) {
        assertThat(expected)
            .as("Verify Action auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActionUpdatableFieldsEquals(Action expected, Action actual) {
        assertThat(expected)
            .as("Verify Action relevant properties")
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getTimestamp()).as("check timestamp").isEqualTo(actual.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActionUpdatableRelationshipsEquals(Action expected, Action actual) {
        // empty method
    }
}
