package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ActivityMatchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityMatchAllPropertiesEquals(ActivityMatch expected, ActivityMatch actual) {
        assertActivityMatchAutoGeneratedPropertiesEquals(expected, actual);
        assertActivityMatchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityMatchAllUpdatablePropertiesEquals(ActivityMatch expected, ActivityMatch actual) {
        assertActivityMatchUpdatableFieldsEquals(expected, actual);
        assertActivityMatchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityMatchAutoGeneratedPropertiesEquals(ActivityMatch expected, ActivityMatch actual) {
        assertThat(expected)
            .as("Verify ActivityMatch auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityMatchUpdatableFieldsEquals(ActivityMatch expected, ActivityMatch actual) {
        assertThat(expected)
            .as("Verify ActivityMatch relevant properties")
            .satisfies(e -> assertThat(e.getActivityType()).as("check activityType").isEqualTo(actual.getActivityType()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityMatchUpdatableRelationshipsEquals(ActivityMatch expected, ActivityMatch actual) {
        // empty method
    }
}
