package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ActivityParticipantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityParticipantAllPropertiesEquals(ActivityParticipant expected, ActivityParticipant actual) {
        assertActivityParticipantAutoGeneratedPropertiesEquals(expected, actual);
        assertActivityParticipantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityParticipantAllUpdatablePropertiesEquals(ActivityParticipant expected, ActivityParticipant actual) {
        assertActivityParticipantUpdatableFieldsEquals(expected, actual);
        assertActivityParticipantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityParticipantAutoGeneratedPropertiesEquals(ActivityParticipant expected, ActivityParticipant actual) {
        assertThat(expected)
            .as("Verify ActivityParticipant auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityParticipantUpdatableFieldsEquals(ActivityParticipant expected, ActivityParticipant actual) {
        assertThat(expected)
            .as("Verify ActivityParticipant relevant properties")
            .satisfies(e -> assertThat(e.getJoinedDate()).as("check joinedDate").isEqualTo(actual.getJoinedDate()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertActivityParticipantUpdatableRelationshipsEquals(ActivityParticipant expected, ActivityParticipant actual) {
        assertThat(expected)
            .as("Verify ActivityParticipant relationships")
            .satisfies(e -> assertThat(e.getParticipant()).as("check participant").isEqualTo(actual.getParticipant()))
            .satisfies(e -> assertThat(e.getActivity()).as("check activity").isEqualTo(actual.getActivity()));
    }
}
