package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChallengeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengeAllPropertiesEquals(Challenge expected, Challenge actual) {
        assertChallengeAutoGeneratedPropertiesEquals(expected, actual);
        assertChallengeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengeAllUpdatablePropertiesEquals(Challenge expected, Challenge actual) {
        assertChallengeUpdatableFieldsEquals(expected, actual);
        assertChallengeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengeAutoGeneratedPropertiesEquals(Challenge expected, Challenge actual) {
        assertThat(expected)
            .as("Verify Challenge auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengeUpdatableFieldsEquals(Challenge expected, Challenge actual) {
        assertThat(expected)
            .as("Verify Challenge relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getCategory()).as("check category").isEqualTo(actual.getCategory()))
            .satisfies(e -> assertThat(e.getPoints()).as("check points").isEqualTo(actual.getPoints()))
            .satisfies(e -> assertThat(e.getBadge()).as("check badge").isEqualTo(actual.getBadge()))
            .satisfies(e -> assertThat(e.getBadgeContentType()).as("check badge contenty type").isEqualTo(actual.getBadgeContentType()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()))
            .satisfies(e -> assertThat(e.getExpiryDate()).as("check expiryDate").isEqualTo(actual.getExpiryDate()))
            .satisfies(e -> assertThat(e.getIsCompleted()).as("check isCompleted").isEqualTo(actual.getIsCompleted()))
            .satisfies(e -> assertThat(e.getCompletedDate()).as("check completedDate").isEqualTo(actual.getCompletedDate()))
            .satisfies(e -> assertThat(e.getIsDisplayed()).as("check isDisplayed").isEqualTo(actual.getIsDisplayed()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengeUpdatableRelationshipsEquals(Challenge expected, Challenge actual) {
        // empty method
    }
}
