package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChallengeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengeAllPropertiesEquals(Challenge expected, Challenge actual) {
        assertChallengeAutoGeneratedPropertiesEquals(expected, actual);
        assertChallengeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengeAllUpdatablePropertiesEquals(Challenge expected, Challenge actual) {
        assertChallengeUpdatableFieldsEquals(expected, actual);
        assertChallengeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengeAutoGeneratedPropertiesEquals(Challenge expected, Challenge actual) {
        assertThat(expected)
            .as("Verify Challenge auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengeUpdatableFieldsEquals(Challenge expected, Challenge actual) {
        assertThat(expected)
            .as("Verify Challenge relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getCategory()).as("check category").isEqualTo(actual.getCategory()))
            .satisfies(e -> assertThat(e.getDate()).as("check date").isEqualTo(actual.getDate()))
            .satisfies(e -> assertThat(e.getPoints()).as("check points").isEqualTo(actual.getPoints()))
            .satisfies(e -> assertThat(e.getBadge()).as("check badge").isEqualTo(actual.getBadge()))
            .satisfies(e -> assertThat(e.getBadgeContentType()).as("check badge contenty type").isEqualTo(actual.getBadgeContentType()))
            .satisfies(e -> assertThat(e.getCompleted()).as("check completed").isEqualTo(actual.getCompleted()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChallengeUpdatableRelationshipsEquals(Challenge expected, Challenge actual) {
        assertThat(expected)
            .as("Verify Challenge relationships")
            .satisfies(e -> assertThat(e.getAssignedTo()).as("check assignedTo").isEqualTo(actual.getAssignedTo()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()));
    }
}
