package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ChatAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatAllPropertiesEquals(Chat expected, Chat actual) {
        assertChatAutoGeneratedPropertiesEquals(expected, actual);
        assertChatAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatAllUpdatablePropertiesEquals(Chat expected, Chat actual) {
        assertChatUpdatableFieldsEquals(expected, actual);
        assertChatUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatAutoGeneratedPropertiesEquals(Chat expected, Chat actual) {
        assertThat(expected)
            .as("Verify Chat auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatUpdatableFieldsEquals(Chat expected, Chat actual) {
        assertThat(expected)
            .as("Verify Chat relevant properties")
            .satisfies(e -> assertThat(e.getMessage()).as("check message").isEqualTo(actual.getMessage()))
            .satisfies(e -> assertThat(e.getTimestamp()).as("check timestamp").isEqualTo(actual.getTimestamp()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getMedia()).as("check media").isEqualTo(actual.getMedia()))
            .satisfies(e -> assertThat(e.getMediaContentType()).as("check media contenty type").isEqualTo(actual.getMediaContentType()))
            .satisfies(e -> assertThat(e.getIsDeleted()).as("check isDeleted").isEqualTo(actual.getIsDeleted()))
            .satisfies(e -> assertThat(e.getCreatedOn()).as("check createdOn").isEqualTo(actual.getCreatedOn()))
            .satisfies(e -> assertThat(e.getUpdatedOn()).as("check updatedOn").isEqualTo(actual.getUpdatedOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertChatUpdatableRelationshipsEquals(Chat expected, Chat actual) {
        assertThat(expected)
            .as("Verify Chat relationships")
            .satisfies(e -> assertThat(e.getThread()).as("check thread").isEqualTo(actual.getThread()))
            .satisfies(e -> assertThat(e.getSender()).as("check sender").isEqualTo(actual.getSender()))
            .satisfies(e -> assertThat(e.getReceiver()).as("check receiver").isEqualTo(actual.getReceiver()))
            .satisfies(e -> assertThat(e.getMessageThread()).as("check messageThread").isEqualTo(actual.getMessageThread()));
    }
}
