package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FriendsListAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendsListAllPropertiesEquals(FriendsList expected, FriendsList actual) {
        assertFriendsListAutoGeneratedPropertiesEquals(expected, actual);
        assertFriendsListAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendsListAllUpdatablePropertiesEquals(FriendsList expected, FriendsList actual) {
        assertFriendsListUpdatableFieldsEquals(expected, actual);
        assertFriendsListUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendsListAutoGeneratedPropertiesEquals(FriendsList expected, FriendsList actual) {
        assertThat(expected)
            .as("Verify FriendsList auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendsListUpdatableFieldsEquals(FriendsList expected, FriendsList actual) {
        assertThat(expected)
            .as("Verify FriendsList relevant properties")
            .satisfies(e -> assertThat(e.getFriendRequest()).as("check friendRequest").isEqualTo(actual.getFriendRequest()))
            .satisfies(e -> assertThat(e.getFriendSince()).as("check friendSince").isEqualTo(actual.getFriendSince()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFriendsListUpdatableRelationshipsEquals(FriendsList expected, FriendsList actual) {
        assertThat(expected)
            .as("Verify FriendsList relationships")
            .satisfies(e -> assertThat(e.getFriends()).as("check friends").isEqualTo(actual.getFriends()));
    }
}
