package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MessageThreadAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageThreadAllPropertiesEquals(MessageThread expected, MessageThread actual) {
        assertMessageThreadAutoGeneratedPropertiesEquals(expected, actual);
        assertMessageThreadAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageThreadAllUpdatablePropertiesEquals(MessageThread expected, MessageThread actual) {
        assertMessageThreadUpdatableFieldsEquals(expected, actual);
        assertMessageThreadUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageThreadAutoGeneratedPropertiesEquals(MessageThread expected, MessageThread actual) {
        assertThat(expected)
            .as("Verify MessageThread auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageThreadUpdatableFieldsEquals(MessageThread expected, MessageThread actual) {
        assertThat(expected)
            .as("Verify MessageThread relevant properties")
            .satisfies(e -> assertThat(e.getIsGroup()).as("check isGroup").isEqualTo(actual.getIsGroup()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getCreatedOn()).as("check createdOn").isEqualTo(actual.getCreatedOn()))
            .satisfies(e -> assertThat(e.getUpdatedOn()).as("check updatedOn").isEqualTo(actual.getUpdatedOn()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMessageThreadUpdatableRelationshipsEquals(MessageThread expected, MessageThread actual) {
        assertThat(expected)
            .as("Verify MessageThread relationships")
            .satisfies(e -> assertThat(e.getFriendChat()).as("check friendChat").isEqualTo(actual.getFriendChat()))
            .satisfies(e -> assertThat(e.getMatchChat()).as("check matchChat").isEqualTo(actual.getMatchChat()))
            .satisfies(e -> assertThat(e.getParticipants()).as("check participants").isEqualTo(actual.getParticipants()));
    }
}
