package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileAllPropertiesEquals(Profile expected, Profile actual) {
        assertProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileAllUpdatablePropertiesEquals(Profile expected, Profile actual) {
        assertProfileUpdatableFieldsEquals(expected, actual);
        assertProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileAutoGeneratedPropertiesEquals(Profile expected, Profile actual) {
        assertThat(expected)
            .as("Verify Profile auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileUpdatableFieldsEquals(Profile expected, Profile actual) {
        assertThat(expected)
            .as("Verify Profile relevant properties")
            .satisfies(e -> assertThat(e.getBio()).as("check bio").isEqualTo(actual.getBio()))
            .satisfies(e -> assertThat(e.getProfilePicture()).as("check profilePicture").isEqualTo(actual.getProfilePicture()))
            .satisfies(e ->
                assertThat(e.getProfilePictureContentType())
                    .as("check profilePicture contenty type")
                    .isEqualTo(actual.getProfilePictureContentType())
            )
            .satisfies(e -> assertThat(e.getCourse()).as("check course").isEqualTo(actual.getCourse()))
            .satisfies(e -> assertThat(e.getCourseYear()).as("check courseYear").isEqualTo(actual.getCourseYear()))
            .satisfies(e -> assertThat(e.getGymSkill()).as("check gymSkill").isEqualTo(actual.getGymSkill()))
            .satisfies(e -> assertThat(e.getGymLocation()).as("check gymLocation").isEqualTo(actual.getGymLocation()))
            .satisfies(e -> assertThat(e.getGymTime()).as("check gymTime").isEqualTo(actual.getGymTime()))
            .satisfies(e -> assertThat(e.getStudyTime()).as("check studyTime").isEqualTo(actual.getStudyTime()))
            .satisfies(e -> assertThat(e.getSports()).as("check sports").isEqualTo(actual.getSports()))
            .satisfies(e -> assertThat(e.getSportsSkill()).as("check sportsSkill").isEqualTo(actual.getSportsSkill()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileUpdatableRelationshipsEquals(Profile expected, Profile actual) {
        // empty method
    }
}
