package bham.team.domain;

import static bham.team.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class RankingAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRankingAllPropertiesEquals(Ranking expected, Ranking actual) {
        assertRankingAutoGeneratedPropertiesEquals(expected, actual);
        assertRankingAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRankingAllUpdatablePropertiesEquals(Ranking expected, Ranking actual) {
        assertRankingUpdatableFieldsEquals(expected, actual);
        assertRankingUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRankingAutoGeneratedPropertiesEquals(Ranking expected, Ranking actual) {
        assertThat(expected)
            .as("Verify Ranking auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRankingUpdatableFieldsEquals(Ranking expected, Ranking actual) {
        assertThat(expected)
            .as("Verify Ranking relevant properties")
            .satisfies(e -> assertThat(e.getReviewNumber()).as("check reviewNumber").isEqualTo(actual.getReviewNumber()))
            .satisfies(e -> assertThat(e.getActivityNumber()).as("check activityNumber").isEqualTo(actual.getActivityNumber()))
            .satisfies(e ->
                assertThat(e.getStarAverage())
                    .as("check starAverage")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(actual.getStarAverage())
            )
            .satisfies(e -> assertThat(e.getReliable()).as("check reliable").isEqualTo(actual.getReliable()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRankingUpdatableRelationshipsEquals(Ranking expected, Ranking actual) {
        assertThat(expected)
            .as("Verify Ranking relationships")
            .satisfies(e -> assertThat(e.getRankGiven()).as("check rankGiven").isEqualTo(actual.getRankGiven()));
    }
}
