package bham.team.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TimeSlotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotAllPropertiesEquals(TimeSlot expected, TimeSlot actual) {
        assertTimeSlotAutoGeneratedPropertiesEquals(expected, actual);
        assertTimeSlotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotAllUpdatablePropertiesEquals(TimeSlot expected, TimeSlot actual) {
        assertTimeSlotUpdatableFieldsEquals(expected, actual);
        assertTimeSlotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotAutoGeneratedPropertiesEquals(TimeSlot expected, TimeSlot actual) {
        assertThat(expected)
            .as("Verify TimeSlot auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotUpdatableFieldsEquals(TimeSlot expected, TimeSlot actual) {
        assertThat(expected)
            .as("Verify TimeSlot relevant properties")
            .satisfies(e -> assertThat(e.getDate()).as("check date").isEqualTo(actual.getDate()))
            .satisfies(e -> assertThat(e.getStartHour()).as("check startHour").isEqualTo(actual.getStartHour()))
            .satisfies(e -> assertThat(e.getEndHour()).as("check endHour").isEqualTo(actual.getEndHour()))
            .satisfies(e -> assertThat(e.getCapacity()).as("check capacity").isEqualTo(actual.getCapacity()))
            .satisfies(e -> assertThat(e.getRemainingCapacity()).as("check remainingCapacity").isEqualTo(actual.getRemainingCapacity()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTimeSlotUpdatableRelationshipsEquals(TimeSlot expected, TimeSlot actual) {
        assertThat(expected)
            .as("Verify TimeSlot relationships")
            .satisfies(e -> assertThat(e.getEvent()).as("check event").isEqualTo(actual.getEvent()));
    }
}
