export enum EventType {
  STUDY_SPACES = 'STUDY_SPACES',

  EVENT_ROOMS = 'EVENT_ROOMS',

  FOOTBALL_PITCH = 'FOOTBALL_PITCH',

  TENNIS_COURT = 'TENNIS_COURT',

  BASKETBALL_COURT = 'BASKETBALL_COURT',

  DOJO = 'DOJO',

  SWIMMING_POOL = 'SWIMMING_POOL',

  SQUASH_COURT = 'SQUASH_COURT',
}
