export enum Notificationstype {
  NEW_CHAT_MESSAGE = 'NEW_CHAT_MESSAGE',

  FRIEND_REQUEST = 'FRIEND_REQUEST',

  ACTIVITY_MATCH = 'ACTIVITY_MATCH',

  BOOKING_CONFIRMATION = 'BOOKING_CONFIRMATION',
}
