export enum PreferredEvents {
  GAMES_NIGHT = 'GAMES_NIGHT',

  MEET_AND_GREET = 'MEET_AND_GREET',

  SPORTS_NIGHT = 'SPORTS_NIGHT',

  CLUBBING = 'CLUBBING',

  RELIGIOUS = 'RELIGIOUS',

  ACADEMIC = 'ACADEMIC',
}
