export enum Society {
  ABACUS = 'ABACUS',

  ACCOUNTING_AND_FINANCE = 'ACCOUNTING_AND_FINANCE',

  AFRICAN_AND_CARIBBEAN = 'AFRICAN_AND_CARIBBEAN',

  ALGOSOC = 'ALGOSOC',

  ARAB = 'ARAB',

  AZERBAIJANI = 'AZERBAIJANI',

  BAKING = 'BAKING',

  BALADS = 'BALADS',

  BENGALI = 'BENGALI',

  BIOSOC = 'BIOSOC',

  BIRMINGHAM_BLACK_AND_ETHNIC_MINORITY_SCIENTISTS = 'BIRMINGHAM_BLACK_AND_ETHNIC_MINORITY_SCIENTISTS',

  BLACK_LAW_STUDENTS_SOCIETY = 'BLACK_LAW_STUDENTS_SOCIETY',

  CANADIAN_SOCIETY = 'CANADIAN_SOCIETY',

  CARIBBEAN_UNION = 'CARIBBEAN_UNION',

  CATHOLIC = 'CATHOLIC',

  CHESS = 'CHESS',

  CIVIL_ENGINEERING = 'CIVIL_ENGINEERING',

  COMPUTER_SCIENCE_SOCIETY = 'COMPUTER_SCIENCE_SOCIETY',

  CRAFT = 'CRAFT',

  CRIMINOLOGY = 'CRIMINOLOGY',

  CULTURAL_ARTS = 'CULTURAL_ARTS',

  DARTS_SOCIETY = 'DARTS_SOCIETY',

  DEBATING = 'DEBATING',

  DENTAL_SOCIETY = 'DENTAL_SOCIETY',

  EAST_AFRICAN = 'EAST_AFRICAN',

  EGYPTIAN = 'EGYPTIAN',

  ELECTRONIC_AND_ELECTRICAL_ENGINEERING = 'ELECTRONIC_AND_ELECTRICAL_ENGINEERING',

  ESPORTS = 'ESPORTS',

  FILIPINO = 'FILIPINO',

  FILMSOC = 'FILMSOC',

  FINTECH = 'FINTECH',

  FRIENDS_OF_PALESTINE = 'FRIENDS_OF_PALESTINE',

  GAMES_DEVELOPMENT = 'GAMES_DEVELOPMENT',

  GERMAN = 'GERMAN',

  HENNA_SOCIETY = 'HENNA_SOCIETY',

  HIDE_AND_SEEK_SOCIETY = 'HIDE_AND_SEEK_SOCIETY',

  HINDU = 'HINDU',

  ICE_SKATING_SOCIETY = 'ICE_SKATING_SOCIETY',

  INDIAN = 'INDIAN',

  IRAQI = 'IRAQI',

  ISLAMIC = 'ISLAMIC',

  ITALIAN = 'ITALIAN',

  JAIN_SOCIETY = 'JAIN_SOCIETY',

  JAPAN_SOCIETY = 'JAPAN_SOCIETY',

  KICKBOXING = 'KICKBOXING',

  KOREA = 'KOREA',

  MALAYALEE = 'MALAYALEE',

  MALAYSIAN = 'MALAYSIAN',

  MATHSOC = 'MATHSOC',

  MEDTEC = 'MEDTEC',

  MIXED_MARTIAL_ARTS = 'MIXED_MARTIAL_ARTS',

  MUAY_THAI_BOXING = 'MUAY_THAI_BOXING',

  NEPALESE = 'NEPALESE',

  NERDSOC = 'NERDSOC',

  NORTH_AFRICAN = 'NORTH_AFRICAN',

  OMANI_SOCIETY = 'OMANI_SOCIETY',

  PAKISTAN = 'PAKISTAN',

  POWERLIFTING = 'POWERLIFTING',

  PSYCHOLOGY = 'PSYCHOLOGY',

  PUNJABI = 'PUNJABI',

  SAUDI = 'SAUDI',

  SHOOTING = 'SHOOTING',

  SIKH = 'SIKH',

  SINGAPORE_SOCIETY = 'SINGAPORE_SOCIETY',

  SRI_LANKAN_SOCIETY = 'SRI_LANKAN_SOCIETY',

  SUDANESE_SOCIETY = 'SUDANESE_SOCIETY',

  TAMIL = 'TAMIL',

  TURKISH = 'TURKISH',

  UKRAINIAN_SOCIETY = 'UKRAINIAN_SOCIETY',

  VIDEO_GAMES_SOCIETY = 'VIDEO_GAMES_SOCIETY',

  VIETNAMESE = 'VIETNAMESE',

  WAYFARERS_HIKING_SOCIETY = 'WAYFARERS_HIKING_SOCIETY',

  WELSH = 'WELSH',

  WOMEN_IN_LAW = 'WOMEN_IN_LAW',

  WOMEN_IN_MEDICINE = 'WOMEN_IN_MEDICINE',

  OTHER = 'OTHER',
}
