export enum University {
  UNIVERSITY_OF_BIRMINGHAM = 'UNIVERSITY_OF_BIRMINGHAM',

  ASTON_UNIVERSITY = 'ASTON_UNIVERSITY',

  BIRMINGHAM_CITY_UNIVERSITY = 'BIRMINGHAM_CITY_UNIVERSITY',

  UNIVERSITY_OF_NOTTINGHAM = 'UNIVERSITY_OF_NOTTINGHAM',
}
